#!/usr/bin/env php
<?php
use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use App\Http\Controllers\WebSocketController;

require dirname(__FILE__) . '/vendor/autoload.php';

$loop   = React\EventLoop\Factory::create();
$webSock = new React\Socket\SecureServer(
	new React\Socket\Server(env('CHAT_SECURE_URL', 8890), $loop),
	$loop,
	array(
        'local_cert'        => '/var/www/html/certs/fullchain.pem', // path to your cert
        'local_pk'          => '/var/www/html/certs/privkey.pem', // path to your server private key
        'verify_peer' => FALSE
	)
);

// Ratchet magic
$webServer = new Ratchet\Server\IoServer(
	new Ratchet\Http\HttpServer(
		new Ratchet\WebSocket\WsServer(
            new WebSocketController()
		)
	),
	$webSock
);

$loop->run();
